import type { NextPage } from "next";
import Head from "next/head";

import ResponsiveIFrame from "@/components/ResponsiveIFrame";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ResponsiveIFrame
        src="https://www.youtube.com/embed/Ht4h6WxEbU0"
        title="[온스테이지2.0] wave to earth - nouvelle vague"
      />
    </div>
  );
};

export default Home;
