import type { NextPage } from "next";
import Head from "next/head";

import { Heading } from "@/components/Typography";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading as="h1">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis magnam,
        unde dicta tenetur natus id, reiciendis perspiciatis, asperiores impedit
        illum aliquid amet dolore ipsum dolorum nam aperiam delectus veritatis
        ea!
      </Heading>
    </div>
  );
};

export default Home;
